# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/whisper-app" # Location of package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      # You can add dependencies here to ignore if they cause breaking changes
      - dependency-name: "electron"
        versions: ["*"] # Ignore electron major updates for stability, do manually
